targets:
   $default:
       builders:
           screengen|screen_tracker:
               enabled: true
builders:
   screen_tracker:
       target: ":screengen"
       import: "package:screengen/builder.dart"
       builder_factories: ["screenTracker"]
       build_extensions: {".dart": [".karee"]}
       auto_apply: dependents
       build_to: cache
       applies_builders: ["source_gen|combining_builder"]