name: screengen
description: Screen generator, this project is used by Karee Core, to generate additional files for Screen.
version: 2.0.0
homepage: https://github.com/ChamplainLeCode/karee_screen_generator.git
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  screen_tracker: ^2.0.0
dev_dependencies:
  analyzer: ^1.0.0